-- Semantic image metadata for the initial Article reading surfaces.
-- Binary files remain in an external image host or Supabase Storage; this table
-- stores their stable URL, intended display role, and attribution metadata.
create table if not exists public.article_images (
  id bigint generated by default as identity primary key,
  article_id bigint not null references public."Article" (id) on delete cascade,
  role text not null check (role in ('cover', 'featured', 'poster')),
  image_url text not null check (length(trim(image_url)) > 0),
  alt_text text,
  source text,
  photographer_name text,
  attribution_url text,
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  unique (article_id, role)
);

create index if not exists article_images_article_id_sort_idx
  on public.article_images (article_id, sort_order);

alter table public.article_images enable row level security;

grant select on table public.article_images to anon, authenticated;

drop policy if exists "Public can read article images" on public.article_images;
create policy "Public can read article images"
  on public.article_images
  for select
  to anon, authenticated
  using (true);

-- Stable Unsplash placeholder images for the four existing placeholder articles.
-- The title match makes this seed portable across copies of the current project.
with image_seed(article_title, role, image_url, alt_text, attribution_url) as (
  values
    (
      '[占位文章] 诗人抵达江南之前',
      'featured',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=85',
      '山间湖畔与晨雾',
      'https://unsplash.com/photos/1500530855697-b586d89ba3ee'
    ),
    (
      '[占位文章] 诗人抵达江南之前',
      'poster',
      'https://images.unsplash.com/photo-1494783367193-149034c05e8f?auto=format&fit=crop&w=480&q=80',
      '山间旅途的小径',
      'https://unsplash.com/photos/1494783367193-149034c05e8f'
    ),
    (
      '[占位文章] 诗人抵达江南之前',
      'cover',
      'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=80',
      '远山与湖水',
      'https://unsplash.com/photos/1470770841072-f978cf4d019e'
    ),
    (
      '[占位文章] 赤壁夜色下的渡口笔记',
      'featured',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=85',
      '群山与河谷的暮色',
      'https://unsplash.com/photos/1469474968028-56623f02e42e'
    ),
    (
      '[占位文章] 赤壁夜色下的渡口笔记',
      'poster',
      'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=480&q=80',
      '山谷中的水面',
      'https://unsplash.com/photos/1500534623283-312aade485b7'
    ),
    (
      '[占位文章] 赤壁夜色下的渡口笔记',
      'cover',
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=80',
      '林间深色小径',
      'https://unsplash.com/photos/1441974231531-c6227db76b6e'
    ),
    (
      '[占位文章] 从校门到旧街巷的半日路线',
      'featured',
      'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1600&q=85',
      '城市中的古老街巷',
      'https://unsplash.com/photos/1528127269322-539801943592'
    ),
    (
      '[占位文章] 从校门到旧街巷的半日路线',
      'poster',
      'https://images.unsplash.com/photo-1444723121867-7a241cacace9?auto=format&fit=crop&w=480&q=80',
      '建筑与街角',
      'https://unsplash.com/photos/1444723121867-7a241cacace9'
    ),
    (
      '[占位文章] 从校门到旧街巷的半日路线',
      'cover',
      'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=800&q=80',
      '书架与阅读空间',
      'https://unsplash.com/photos/1481627834876-b7833e8f5570'
    ),
    (
      '[占位文章] 午后手稿与一盏茶',
      'featured',
      'https://images.unsplash.com/photo-1490730141103-6cac27aaab94?auto=format&fit=crop&w=1600&q=85',
      '安静的午后书桌',
      'https://unsplash.com/photos/1490730141103-6cac27aaab94'
    ),
    (
      '[占位文章] 午后手稿与一盏茶',
      'poster',
      'https://images.unsplash.com/photo-1511081692775-05d0f180a065?auto=format&fit=crop&w=480&q=80',
      '手写笔记与茶杯',
      'https://unsplash.com/photos/1511081692775-05d0f180a065'
    ),
    (
      '[占位文章] 午后手稿与一盏茶',
      'cover',
      'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=800&q=80',
      '纸张与写作工具',
      'https://unsplash.com/photos/1499750310107-5fef28a66643'
    )
)
insert into public.article_images (
  article_id,
  role,
  image_url,
  alt_text,
  source,
  attribution_url
)
select
  article.id,
  image_seed.role,
  image_seed.image_url,
  image_seed.alt_text,
  'unsplash',
  image_seed.attribution_url
from image_seed
join public."Article" as article on article.title = image_seed.article_title
on conflict (article_id, role) do update
set
  image_url = excluded.image_url,
  alt_text = excluded.alt_text,
  source = excluded.source,
  attribution_url = excluded.attribution_url;
